pipeline {
    agent any
    parameters {
        booleanParam(name: 'RC', defaultValue: false, description: 'Is this a Release Candidate?')
    }
    environment {
        RELEASE='20.04'
    }
    stages {
            auditTools()
        }
        stage('Build') {
            agent any
            environment {
                LOG_LEVEL='INFO'
            }
            steps {
                echo "Building release ${RELEASE} with log level ${LOG_LEVEL}..."
            }
        }
        stage('Test') {
            steps {
                echo "Testing release ${RELEASE}..."
            }
        }
    
        stage('Deploy') {
            input {
              message 'Deploy????'
              parameters {
                    string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target deployment environment')
              }
            }
            steps {
                echo "Deploying release ${RELEASE} to environment ${TARGET_ENVIRONMENT}"
                writeFile file: 'test-results.txt', text: "Deploying release ${RELEASE} to environment ${TARGET_ENVIRONMENT}"
            }
        }
    
            stage('Release') {
                when {
                    expression { return params.RC }
            } 
            steps {

                echo "Now releasing Artifacr ${RELEASE}..."
                archiveArtifacts 'test-results.txt'

            }
        }
    }
            post {
          always {
             echo 'Prints whether deploy happened or not, success or failure'
          }
        }
    
}


void auditTools() {
    sh '''
        git version
        docker version
    '''
}